freelance_project/urls.py
from django.contrib import admin
from django.urls import path, re_path
from freelance_app.views import *
from freelance_app import views



urlpatterns = [
    path('admin/', admin.site.urls),
    path('', start_page, name='start_page'),
    path('login/', views.MyprojectLoginView.as_view(), name='login_page'),
    path('register/', views.RegisterUserView.as_view(), name='register_page'),
    #path('orders/all', OrderListView.as_view()),
    #path('orders/<int:pk>', OrderRetrieveView.as_view()),
    path('customer/create_order', create_order, name='create_order'),
    path('create_user/', create_user, name='create_user'),
    path('freelancer/main_page', freelancer_main_page, name='freelancer_main_page'),
    path('customer/customer_main_page', customer_main_page, name='customer_main_page'),
    path('orders/add', add_order, name='add_order'),
    path('orders/all', OrderViewAll.as_view(), name='all_orders'),
    path('orders/update/<int:pk>', OrderUpdateView.as_view(), name='update_order'),
<<<<<<< HEAD
    re_path(r'customer/customer_main_page/my_orders/order_responses/(?P<order_id>\w+)/$', order_responses, name="order_responses"),
    re_path(r'customer/customer_main_page/my_orders/order_responses/.*?/(?P<pk>\w+)/$', assign_to_order),
    re_path(r'customer/customer_main_page/my_orders/order_responses/.*?/(?P<pk>\w+)/remove$', remove_from_order),
    # Все нижние Никитины
    path('freelancer/main_page/free_orders/chose/<int:pk>', update_offers),
    path('freelancer/main_page/my_works', freelancer_my_works, name='my_works'),
    path('freelancer/main_page/free_orders/refuse/<int:pk>', refuse_offer),
    path('freelancer/main_page/my_works/save_answer/<int:pk>', freelancer_my_works),
    path('customer/customer_main_page/my_orders/accept/<int:pk>', accept_order),
    path('customer/customer_main_page/my_orders/rate/<int:pk>', customer_main_page),
    path('customer/customer_main_page/my_orders/reject/<int:pk>', refuse_order),
    #новое
    path('customer/customer_main_page/my_orders', my_orders, name='my_orders'),
    path('freelancer/main_page/free_orders', free_orders, name='free_orders'),
=======
    re_path(r'customer/customer_main_page/order_responses/(?P<order_id>\w+)/$', order_responses, name="order_responses"),
    re_path(r'customer/customer_main_page/order_responses/.*?/(?P<pk>\w+)/$', assign_to_order),
    re_path(r'customer/customer_main_page/order_responses/.*?/(?P<pk>\w+)/remove$', remove_from_order),
    # Все нижние Никитины
    path('freelancer/main_page/chose/<int:pk>', update_offers),
    path('freelancer/main_page/my_works', freelancer_my_works, name='my_works'),
    path('freelancer/main_page/refuse/<int:pk>', refuse_offer),
    path('freelancer/main_page/my_works/save_answer/<int:pk>', freelancer_my_works),
    path('customer/customer_main_page/accept/<int:pk>', accept_order),
    path('customer/customer_main_page/rate/<int:pk>', customer_main_page),
    path('customer/customer_main_page/reject/<int:pk>', refuse_order),
    #новое
>>>>>>> 254a8fee79cb304890d74e67445b534a6482c802
    path('customer/customer_main_page/balance', my_balance, name='my_balance_customer'),
    path('freelancer/main_page/balance', my_balance, name='my_balance_freelancer'),
    path('customer/customer_main_page/deal_history', show_deal_history),
    path('freelancer/main_page/deal_history', show_deal_history),
<<<<<<< HEAD
    path('customer/customer_main_page/my_orders/delete_order/<int:pk>', delete_order)
=======
    path('customer/customer_main_page/delete_order/<int:pk>', delete_order)
>>>>>>> 254a8fee79cb304890d74e67445b534a6482c802

]

freelance_app/models.py
from django.db import models
from django.contrib.auth.models import User


class UserData(models.Model):
    django_user_id = models.ForeignKey(User, on_delete=models.CASCADE)
    last_name = models.CharField(max_length=30)
    first_name = models.CharField(max_length=30)
    mail = models.EmailField()
    # password = models.CharField(max_length=20)
    bank_account = models.CharField(max_length=50)
    role = models.IntegerField(choices=[(0, 'Фрилансер'), (1, 'Заказчик')])
    about = models.CharField(max_length=150, null=True)


    def __str__(self):
        return f'{self.last_name}, {self.first_name}, {self.mail}, {self.bank_account}, {self.role},' \
               f'{self.about}, {self.django_user_id}'


class Freelancer(models.Model):
    user_id = models.ForeignKey(UserData, on_delete=models.CASCADE)
    degree = models.IntegerField(default=0)

    def __str__(self):
        return f'{self.user_id}, {self.degree}'


class Customer(models.Model):
    user_id = models.ForeignKey(UserData, on_delete=models.CASCADE)
    degree = models.IntegerField(default=0)

    def __str__(self):
        return f'{self.user_id}, {self.degree}'


class Category(models.Model): # у нас две категории.0 индекс-дизайн, 1 индекс-разработка
    description = models.CharField(max_length=50)

    def __str__(self):
        return self.description


class Order(models.Model):
    customer = models.ForeignKey(Customer, on_delete=models.CASCADE)
    explanation = models.CharField(max_length=200)
    cost = models.IntegerField()
    in_work = models.BooleanField(default=False)
    performer = models.ForeignKey(Freelancer, on_delete=models.CASCADE, null=True, blank=True)
    degree_to_company = models.IntegerField(
        choices=[(0, 'Оценки нет'), (1, 'Очень плохо'), (2, "Плохо"), (3, "Средне"), (4, "Хорошо"), (5, "Отлично")], null=True, blank=True)
    degree_to_performer = models.IntegerField(
        choices=[(0, 'Оценки нет'), (1, 'Очень плохо'), (2, "Плохо"), (3, "Средне"), (4, "Хорошо"), (5, "Отлично")], null=True, blank=True)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    deadline = models.DateField()
    done = models.BooleanField(default=False)
    work_ready = models.CharField(max_length=200, null=True, blank=True)

    def __str__(self):
        return f'{self.customer}, {self.explanation}, {self.cost}, {self.in_work}, {self.performer}, {self.degree_to_company},' \
               f'{self.degree_to_performer}, {self.category}, {self.deadline}, {self.done}'


class Offers(models.Model):
    details = models.ForeignKey(Order, on_delete=models.CASCADE)
    freelance_variety = models.ForeignKey(Freelancer, on_delete=models.CASCADE)
    take = models.BooleanField(default=False)

    def __str__(self):
        return f'{self.details}, {self.freelance_variety}, {self.take}'


class DealHistory(models.Model):
    from_who = models.ForeignKey(UserData, on_delete=models.CASCADE, related_name='deals_sent')
    to_who = models.ForeignKey(UserData, on_delete=models.CASCADE, related_name='deals_received')
    order = models.ForeignKey(Order, on_delete=models.CASCADE)

    def __str__(self):
        return f'{self.from_who}, {self.to_who}, {self.order}'


class BalanceOperations(models.Model):
    user_id = models.ForeignKey(UserData, on_delete=models.CASCADE)
    type_operation = models.IntegerField(choices=[(0, 'Вывод средств'), (1, 'Пополнение')])
    summa = models.IntegerField()

    def __str__(self):
        return f'{self.user_id}, {self.type_operation}, {self.summa}'

templates/Balance_update.html
{% load static %}

{% block content %}
<p>Мой баланс: {{balance}}</p>

{% if user_id.role == 1 %}
    <p>Обратите внимание, что сумма вывода средств не должна превышать суммарную сумму стоимостей созданных заказов.</p>
    <form action= "{% url 'my_balance_customer' %}" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button class="btn btn-success" type="submit">Произвести операцию</button>
    </form>
{% else %}
    <form action= "{% url 'my_balance_freelancer' %}" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button class="btn btn-success" type="submit">Произвести операцию</button>
    </form>
{% endif %}
{% endblock %}

templates/deal_history.html
<!DOCTYPE html>
<<<<<<< HEAD
{% load static %}
<html lang="en" data-bs-theme="light">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="keywords" content="">
    <meta name="author" content="">
    <meta name="robots" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="Dompet : Payment Admin Template">
    <meta property="og:title" content="Dompet : Payment Admin Template">
    <meta property="og:description" content="Dompet : Payment Admin Template">
    <meta property="og:image" content="https://dompet.dexignlab.com/xhtml/social-image.png">
    <meta name="format-detection" content="telephone=no">

    <!-- PAGE TITLE HERE -->
    <title>История операций</title>

    <!-- FAVICONS ICON -->
    <link rel="shortcut icon" type="image/png" href="{% static 'images/favicon.png' %}">
    <link href="{% static 'bootstrap/vendor/jquery-nice-select/css/nice-select.css' %}" rel="stylesheet">
    <link href="{% static 'bootstrap/vendor/nouislider/nouislider.min.css' %}" rel="stylesheet">
    <!-- Style css -->
    <link href="{% static 'bootstrap/css/styless.css' %}" rel="stylesheet">
</head>
<body>
{% csrf_token %}

<div class="row">
    <div class="col-xl-3 col-xxl-7">
    </div>
    <div class="col-xl-3 col-xxl-5">
    </div>
    <div class="col-xl-6 col-xxl-7">
    </div>
    <div class="col-xl-6 col-xxl-12">
        <div class="card">
            <div class="card-header d-block d-sm-flex border-0">
                <div class="me-3">
                    <h4 class="card-title mb-2">История операций</h4>
                    <span class="fs-12">Все пополнения и снятия</span>
                </div>
                <div class="card-tabs mt-3 mt-sm-0">
                    {% csrf_token %}
                    {% for p in deal_history %}
                </div>
            </div>
            <div class="card-body tab-content p-0">
                <div class="tab-pane active show fade" id="monthly" role="tabpanel">
                    <div class="table-responsive">
                        <table class="table table-responsive-md card-table transactions-table">
                            <tbody>
                                <tr>
                                    <td>

                                       <svg class="bgl-danger tr-icon" width="63" height="63" viewBox="0 0 63 63" fill="none" xmlns="http://www.w3.org/2000/svg">
															<g><path d="M35.2219 19.0125C34.8937 19.6906 35.1836 20.5109 35.8617 20.8391C37.7484 21.7469 39.3453 23.1578 40.4828 24.9242C41.6476 26.7344 42.2656 28.8344 42.2656 31C42.2656 37.2125 37.2125 42.2656 31 42.2656C24.7875 42.2656 19.7344 37.2125 19.7344 31C19.7344 28.8344 20.3523 26.7344 21.5117 24.9187C22.6437 23.1523 24.2461 21.7414 26.1328 20.8336C26.8109 20.5055 27.1008 19.6906 26.7726 19.007C26.4445 18.3289 25.6297 18.0391 24.9461 18.3672C22.6 19.4937 20.6148 21.2437 19.2094 23.4422C17.7656 25.6953 17 28.3094 17 31C17 34.7406 18.4547 38.257 21.1015 40.8984C23.743 43.5453 27.2594 45 31 45C34.7406 45 38.257 43.5453 40.8984 40.8984C43.5453 38.2516 45 34.7406 45 31C45 28.3094 44.2344 25.6953 42.7851 23.4422C41.3742 21.2492 39.389 19.4937 37.0484 18.3672C36.3648 18.0445 35.55 18.3289 35.2219 19.0125Z" fill="#FF2E2E"></path><path d="M36.3211 30.2726C36.589 30.0047 36.7203 29.6547 36.7203 29.3047C36.7203 28.9547 36.589 28.6047 36.3211 28.3367L32.8812 24.8969C32.3781 24.3937 31.7109 24.1203 31.0055 24.1203C30.3 24.1203 29.6273 24.3992 29.1297 24.8969L25.6898 28.3367C25.1539 28.8726 25.1539 29.7367 25.6898 30.2726C26.2258 30.8086 27.0898 30.8086 27.6258 30.2726L29.6437 28.2547L29.6437 36.0258C29.6437 36.7804 30.2562 37.3929 31.0109 37.3929C31.7656 37.3929 32.3781 36.7804 32.3781 36.0258L32.3781 28.2492L34.3961 30.2672C34.9211 30.8031 35.7851 30.8031 36.3211 30.2726Z" fill="#FF2E2E"></path></g>
														</svg>

                                    </td>
                                    <td>
                                        <h6 class="fs-16 font-w600 mb-0"><a href="javascript:void(0);" class="text-black">Номер заказа: {{ p.order.id }}</a></h6>
                                        <span class="fs-14">{{ p.get_type_operation_display }}</span>
                                    </td>
                                    <td>
                                        <h6 class="fs-16 text-black font-w600 mb-0"> От: {{ p.from_who.last_name }} {{ p.from_who.first_name }}</h6>
                                        <span class="fs-14">Кому: {{ p.to_who.last_name }} {{ p.to_who.first_name }}</span>
                                    </td>

                                    <td><span class="fs-16 text-black font-w600">–{{ p.order.cost }}</span></td>
                                    <td><span class="text-success fs-16 font-w500 text-end d-block">Выполнено</span></td>
                                </tr>
                                {% endfor %}
                             {% for p in balance_operations %}
    <tr>
        <td>
            {% if p.get_type_operation_display == 'Вывод средств' %}
            <svg class="bgl-danger tr-icon" width="63" height="63" viewBox="0 0 63 63" fill="none" xmlns="http://www.w3.org/2000/svg">
															<g><path d="M35.2219 19.0125C34.8937 19.6906 35.1836 20.5109 35.8617 20.8391C37.7484 21.7469 39.3453 23.1578 40.4828 24.9242C41.6476 26.7344 42.2656 28.8344 42.2656 31C42.2656 37.2125 37.2125 42.2656 31 42.2656C24.7875 42.2656 19.7344 37.2125 19.7344 31C19.7344 28.8344 20.3523 26.7344 21.5117 24.9187C22.6437 23.1523 24.2461 21.7414 26.1328 20.8336C26.8109 20.5055 27.1008 19.6906 26.7726 19.007C26.4445 18.3289 25.6297 18.0391 24.9461 18.3672C22.6 19.4937 20.6148 21.2437 19.2094 23.4422C17.7656 25.6953 17 28.3094 17 31C17 34.7406 18.4547 38.257 21.1015 40.8984C23.743 43.5453 27.2594 45 31 45C34.7406 45 38.257 43.5453 40.8984 40.8984C43.5453 38.2516 45 34.7406 45 31C45 28.3094 44.2344 25.6953 42.7851 23.4422C41.3742 21.2492 39.389 19.4937 37.0484 18.3672C36.3648 18.0445 35.55 18.3289 35.2219 19.0125Z" fill="#FF2E2E"></path><path d="M36.3211 30.2726C36.589 30.0047 36.7203 29.6547 36.7203 29.3047C36.7203 28.9547 36.589 28.6047 36.3211 28.3367L32.8812 24.8969C32.3781 24.3937 31.7109 24.1203 31.0055 24.1203C30.3 24.1203 29.6273 24.3992 29.1297 24.8969L25.6898 28.3367C25.1539 28.8726 25.1539 29.7367 25.6898 30.2726C26.2258 30.8086 27.0898 30.8086 27.6258 30.2726L29.6437 28.2547L29.6437 36.0258C29.6437 36.7804 30.2562 37.3929 31.0109 37.3929C31.7656 37.3929 32.3781 36.7804 32.3781 36.0258L32.3781 28.2492L34.3961 30.2672C34.9211 30.8031 35.7851 30.8031 36.3211 30.2726Z" fill="#FF2E2E"></path></g>
														</svg>
            {% elif p.get_type_operation_display == 'Пополнение' %}
            <svg class="bgl-success tr-icon" width="63" height="63" viewBox="0 0 63 63" fill="none" xmlns="http://www.w3.org/2000/svg">
															<g><path d="M35.2219 42.9875C34.8938 42.3094 35.1836 41.4891 35.8617 41.1609C37.7484 40.2531 39.3453 38.8422 40.4828 37.0758C41.6477 35.2656 42.2656 33.1656 42.2656 31C42.2656 24.7875 37.2125 19.7344 31 19.7344C24.7875 19.7344 19.7344 24.7875 19.7344 31C19.7344 33.1656 20.3523 35.2656 21.5117 37.0813C22.6437 38.8477 24.2461 40.2586 26.1328 41.1664C26.8109 41.4945 27.1008 42.3094 26.7727 42.993C26.4445 43.6711 25.6297 43.9609 24.9461 43.6328C22.6 42.5063 20.6148 40.7563 19.2094 38.5578C17.7656 36.3047 17 33.6906 17 31C17 27.2594 18.4547 23.743 21.1016 21.1016C23.743 18.4547 27.2594 17 31 17C34.7406 17 38.257 18.4547 40.8984 21.1016C43.5453 23.7484 45 27.2594 45 31C45 33.6906 44.2344 36.3047 42.7852 38.5578C41.3742 40.7508 39.3891 42.5063 37.0484 43.6328C36.3648 43.9555 35.55 43.6711 35.2219 42.9875Z" fill="#2BC155"></path><path d="M36.3211 31.7274C36.5891 31.9953 36.7203 32.3453 36.7203 32.6953C36.7203 33.0453 36.5891 33.3953 36.3211 33.6633L32.8812 37.1031C32.3781 37.6063 31.7109 37.8797 31.0055 37.8797C30.3 37.8797 29.6273 37.6008 29.1297 37.1031L25.6898 33.6633C25.1539 33.1274 25.1539 32.2633 25.6898 31.7274C26.2258 31.1914 27.0898 31.1914 27.6258 31.7274L29.6437 33.7453L29.6437 25.9742C29.6437 25.2196 30.2562 24.6071 31.0109 24.6071C31.7656 24.6071 32.3781 25.2196 32.3781 25.9742L32.3781 33.7508L34.3961 31.7328C34.9211 31.1969 35.7852 31.1969 36.3211 31.7274Z" fill="#2BC155"></path>
															</g>
														</svg>
            {% endif %}
        </td>
        <td>
            <h6 class="fs-16 font-w600 mb-0"><a href="javascript:void(0);" class="text-black">{{ p.get_type_operation_display }}</a></h6>
        </td>
        <td>
            <h6 class="fs-16 text-black font-w600 mb-0">{{ p.from_who.user_id.last_name }} {{ p.from_who.user_id.first_name }}</h6>
            <span class="fs-14"></span>
        </td>
        <td>
    {% if p.get_type_operation_display == 'Вывод средств' %}
        <span class="fs-16 text-black font-w600">–{{ p.summa }}</span>
    {% elif p.get_type_operation_display == 'Пополнение' %}
        <span class="fs-16 text-black font-w600">+{{ p.summa }}</span>
    {% endif %}
</td>

        <td><span class="text-success fs-16 font-w500 text-end d-block">Выполнено</span></td>
    </tr>
{% endfor %}

                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<!-- External JS -->
<script src="{% static 'bootstrap/vendor/jquery/jquery.min.js' %}"></script>
<script src="{% static 'bootstrap/vendor/jquery/jquery-3.5.1.slim.min.js' %}"></script>
<script src="{% static 'bootstrap/vendor/bootstrap/js/popper.min.js' %}"></script>
<script src="{% static 'bootstrap/vendor/bootstrap/js/bootstrap.min.js' %}"></script>
<script src="{% static 'bootstrap/vendor/jquery-slimscroll/jquery.slimscroll.min.js' %}"></script>
<script src="{% static 'bootstrap/vendor/select2/js/select2.full.min.js' %}"></script>
<script src="{% static 'bootstrap/vendor/nouislider/nouislider.min.js' %}"></script>
<script src="{% static 'bootstrap/vendor/jquery-nice-select/js/jquery.nice-select.min.js' %}"></script>
<script src="{% static 'bootstrap/vendor/multiselect/js/jquery.multi-select.js' %}"></script>
<script src="{% static 'bootstrap/js/plugin.js' %}"></script>

<!-- Main JS -->
<script src="{% static 'bootstrap/js/main.js' %}"></script>

</body>
</html>
=======
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>История сделок</title>
</head>
<body>
{% csrf_token %}
{% for p in deal_history %}
<p>ID заказа: {{p.order.id}} </p>
<p>От кого: {{p.from_who}} </p>
<p>Кому: {{p.to_who}} </p>
<p>Сумма: {{p.order.cost}} </p>
<p>----------------------------</p>
{% endfor %}
{% for p in balance_operations %}
<p>Тип операции: {{p.get_type_operation_display}}
<p>Сумма: {{p.summa}}</p>
<p>-----------------------------</p>
{% endfor %}
</body>
</html>
>>>>>>> 254a8fee79cb304890d74e67445b534a6482c802

templates/my_orders.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Мои заказы</title>
    <link href='https://fonts.googleapis.com/css?family=Roboto:400,100,300,700' rel='stylesheet' type='text/css'>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css">

    <link href="{% static 'bootstrap/css/score.css' %}" rel="stylesheet">
    <style>
/* Стиль для жирной зеленой галочки */
.checkmark {
    color: green;
    font-weight: bold;
}

/* Стиль для жирного красного крестика */
.cross {
    color: red;
    font-weight: bold;


    </style>
</head>
<body>
<section class="ftco-section">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-6 text-center mb-5">
                <h1>Мои заказы</h1>
            </div>
        </div>
        <div class="row">
            <div class="col-md-12">
                <div class="table-wrap">
                    <table class="table table-striped">
                        <thead>
                        <tr>
                            <th>Описание</th>
                            <th>Цена</th>
                            <th>Категория</th>
                            <th>Выдано исполнителю</th>
                            <th>Статус готовности</th>
                            <th>Исполнитель</th>
                            <th>Ответ</th>
                        </tr>
                        </thead>
                        <tbody>
                        {% for p, k in object_list %}
                        <tr>
                            <td>{{ p.explanation }}</td>
                            <td>{{ p.cost }}</td>
                            <td>{{ p.category }}</td>
                            <td>
                                {% if p.in_work %}
                                <i class="fas fa-check checkmark fa-2x"></i> <!-- Checkmark icon when p.done is True -->
                              {% else %}
                                <i class="fas fa-times cross fa-2x"></i> <!-- Cross icon when p.done is False -->
                              {% endif %}</td>
                             <td>
                                {% if p.done %}
                                <i class="fas fa-check checkmark fa-2x"></i> <!-- Checkmark icon when p.done is True -->
                              {% else %}
                                <i class="fas fa-times cross fa-2x"></i> <!-- Cross icon when p.done is False -->
                              {% endif %}</td>
                            <td>{{ p.performer.user_id.last_name}} {{ p.performer.user_id.first_name}}</td>



                            <td>
    {% if p.work_ready == None %}
        <p>Ответ: отсутствует</p>
    {% elif k == False %}
        <p>Ответ исполнителя: {{p.work_ready}}</p>
    {% elif k == True %}
        <p>Ответ исполнителя не принят: {{p.work_ready}}</p>
    {% endif %}
       <!-- Кнопки в этом же поле ответа исполнителя, если ответа нет, то кнопок нет -->
    {% if p.done == False and p.performer != None and p.work_ready != None and k == False %}
      <a href="my_orders/accept/{{p.id}}">
      <button>Принять ответ</button>
      </a>
      <p></p>
      <a href="my_orders/reject/{{p.id}}">
      <button>Отклонить ответ</button>
      </a>
        <!-- Сделать модальное окно успеха "Заказ был принят" и оценка -->
    {% elif p.done == True and p.degree_to_performer == None %}
      <p>Заказ был принят.</p>
      <form name="Оценка" action="my_orders/rate/{{p.id}}" method="post">
              <label>Оцените исполнителя </label>
                {% csrf_token %}
              {{ form.degree }}
              <button type="submit">Оценить</button>
            </form>
            <!-- Появляется после принятия заказа и оценки исполнителя -->
    {% elif p.done == True and p.performer != None and p.work_ready != None %}
      <p>Ваша оценка исполнителю: {{p.get_degree_to_performer_display}}</p>
    {% endif %}
      <p></p>
      {% if p.performer == None %}
        <a href="my_orders/order_responses/{{p.pk}}">
               <!-- Старое -->
        <button>На Ваш заказ откликнулись</button>
        </a>
      {% endif %}
      <p></p>
      {% if p.in_work == 0 %}
        <a href="my_orders/delete_order/{{p.pk}}">
        <button>Отменить заказ</button>
        </a>
      {% endif %}
                        </td>

{% endfor %}


</table>
                </div>
            </div>
        </div>

</section>

<script src="{% static 'bootstrap/js/jquery.min.js' %}"></script>
<script src="{% static 'bootstrap/js/popper.js' %}"></script>
<script src="{% static 'bootstrap/js/bootstrap.min.js' %}"></script>
<script src="{% static 'bootstrap/js/main.js' %}"></script>

</body>
</html>

templates/new.html
{% for order in object_list %}
  <div>
    <p>Описание - {{ order.explanation }}</p>
    <p>Заказчик {{ order.customer.user_id.last_name }} {{ order.customer.user_id.first_name }}</p>
    <p>Цена {{ order.cost }}</p>
    <p>Дедлайн {{ order.deadline }}</p>
    <p></p>
    {% if order.some_condition %} {# Replace with your condition #}
      <a href="main_page/refuse/{{ order.id }}">
        <button>Вы откликнулись</button>
      </a>
    {% else %}
      <a href="main_page/chose/{{ order.id }}">
        <button>Откликнуться</button>
      </a>
    {% endif %}
    <p>-----------------------------------------------</p>
  </div>
{% endfor %}

templates/order_responses.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
{% for offer in user_offers %}
    <p> Заказ: {{ offer.details.explanation }} </p>
    <p> Имя Фрилансера:{{ offer.freelance_variety.user_id.last_name }} {{ offer.freelance_variety.user_id.first_name }} </p>
    <p> Оценка: {{ offer.freelance_variety.degree }} </p>
    <p> Категория: {{ offer.details.category }} </p>
    {% if offer.take %}
    <a href="./{{offer.pk}}/remove">
     <button>Убрать с заказа</button>
        </a>
    {% else %}
    <a href="./{{offer.pk}}">
        <button>Назначить на заказ</button>
        </a>
    {% endif %}
    <p>-----------------------------------------------</p>
{% endfor %}
</body>
</html>

templates/update_order.html
{% load static %}

{% block content %}

<h1></h1>

<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Обновить</button>
</form>

{% endblock %}